title: Jensen Chen's Homepage
page-top-title: Jensen Chen
top-section-bg-text: Welcome to Jensen Chen's Homepage
home-subtitle: Jinxiang Chen&ensp;|&ensp;陈劲翔
copyright-text: '&copy; JxChen 2025-2035. All Rights Reserved.'
