title: jxChen's Homepage
page-top-title: Jinxiang Chen
top-section-bg-text: Genshin impact, start!
home-subtitle: Jinxiang Chen&ensp;|&ensp;陈劲翔
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
