title: jxChen's Homepage
page-top-title: Jinxiang Chen
top-section-bg-text: Genshin impact, start!
home-subtitle: Jinxiang Chen&ensp;|&ensp;陈劲翔
copyright-text: '&copy; JxChen 2025-2035. All Rights Reserved.'
